name: 'Gravitas Designs  '
favicon: null
layout_spectrum: 0.8565208
typography_spectrum: 0.258245
title: Design With Substance and Imagination
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.05436079
  lightness: 0.007314176
  saturation: 0.2618692
  rhythmicContrast: 0.6249931
purpose: []
